[ip]
name    = "toolbox"
library = "util"
version = "0.1.0"
vendor  = "crus"
summary = "helper functions for validation and verification"
repository = "https://github.com/c-rus/toolbox.git"

# To learn more about writing the manifest, see https://c-rus.github.io/orbit/4_topic/2_orbittoml.html

[dependencies]
